version: '3.3'

services:
  db:
    image: postgres:15
    container_name: foodgram-db
    restart: always
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    build: ../backend
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../backend/:/app
      - static_data:/app/static
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: foodgram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_data:/var/html/static/
      - ./backend/media:/var/html/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_data:
  media_data:
